# Generated by Django 3.0.2 on 2020-02-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textRUS',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='titleRUS',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
