# Generated by Django 3.0.2 on 2020-02-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200225_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textENG',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='titleENG',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
